[package]
name = "brimstone_serialized_heap"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
brimstone_core = { path = "../js", default-features = false }

[build-dependencies]
brimstone_core = { path = "../js", default-features = false }

[features]
default = []
no_jemalloc = ["brimstone_core/no_jemalloc"]