[package]
name = "brimstone_ffi"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
brimstone_core = { workspace = true, default-features = false }
brimstone_serialized_heap = { workspace = true, default-features = false }

[features]
default = []

[lints]
workspace = true
